# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghx < Formula
  desc "AI-Powered GitHub Workflow TUI Assistant"
  homepage "https://github.com/KDM-cli/ghx"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KDM-cli/ghx/releases/download/v0.1.0/ghx_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "55c8a632eceed3264a0cdbd69b8b2ba9c27b5a456123c678e0c8ffb9fc963682"

      define_method(:install) do
        bin.install "ghx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KDM-cli/ghx/releases/download/v0.1.0/ghx_0.1.0_Darwin_arm64.tar.gz"
      sha256 "f095dd8411a3ee7899896fc23876399d9aa093df9aef90ff1db3328dc9684c64"

      define_method(:install) do
        bin.install "ghx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KDM-cli/ghx/releases/download/v0.1.0/ghx_0.1.0_Linux_x86_64.tar.gz"
      sha256 "c83c8a8434b616f4b87958c8f6bce237c55cc15e465aa94a722732594c8b6f31"
      define_method(:install) do
        bin.install "ghx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KDM-cli/ghx/releases/download/v0.1.0/ghx_0.1.0_Linux_arm64.tar.gz"
      sha256 "7f2a7391d0ad16e4efd78254f273bd8c8d868379d62a6e8e0d8a5f6c7cab99cd"
      define_method(:install) do
        bin.install "ghx"
      end
    end
  end

  test do
    system "#{bin}/ghx --version"
  end
end
